import type { CaseLogo } from "@/components/ui/cases-with-infinite-scroll";

export const clientLogos: CaseLogo[] = [
  { name: "Lupin", src: "/logos/clients/lupin.webp" },
  { name: "Premas Biotech", src: "/logos/clients/premas-biotech.webp" },
  { name: "Abbott", src: "/logos/clients/abbott.webp" },
  { name: "Alkem", src: "/logos/clients/alkem.webp" },
  { name: "Amneal", src: "/logos/clients/amneal.webp" },
  { name: "Apothecon Pharmaceuticals", src: "/logos/clients/apothecon.webp" },
  { name: "Aurobindo", src: "/logos/clients/aurobindo.webp" },
  { name: "Biocon", src: "/logos/clients/biocon.webp" },
  { name: "Cipla", src: "/logos/clients/cipla.webp" },
  { name: "Mankind", src: "/logos/clients/mankind.webp" },
  { name: "GSK", src: "/logos/clients/gsk.webp" },
  { name: "Cadila Pharmaceuticals", src: "/logos/clients/cadila.webp" },
  { name: "Sanofi", src: "/logos/clients/sanofi.webp" },
  { name: "Glenmark", src: "/logos/clients/glenmark.webp" },
  { name: "Divi's", src: "/logos/clients/divis.webp" },
  { name: "Dr. Reddy's", src: "/logos/clients/dr-reddys.webp" },
  { name: "Alembic", src: "/logos/clients/alembic.webp" },
  { name: "Sai Life Sciences", src: "/logos/clients/sai-life-sciences.webp" },
  {
    name: "Jubilant Life Sciences",
    src: "/logos/clients/jubilant-life-sciences.webp",
  },
  { name: "Intas Pharmaceuticals", src: "/logos/clients/intas.webp" },
  { name: "SimSon Pharma", src: "/logos/clients/simson-pharma.webp" },
  { name: "Sun Pharma", src: "/logos/clients/sun-pharma.webp" },
  { name: "Neuland", src: "/logos/clients/neuland.webp" },
  { name: "Natco", src: "/logos/clients/natco.webp" },
  { name: "Sumar Biotech", src: "/logos/clients/sumar-biotech.webp" },
  { name: "Torrent Pharma", src: "/logos/clients/torrent-pharma.webp" },
  { name: "Apicore", src: "/logos/clients/apicore.webp" },
  { name: "Zydus", src: "/logos/clients/zydus.webp" },
];
